spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/link
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root